### ISSUE TITLE
Question: Is the benchmark results reliable?

### ISSUE THREAD

**Issue by ghost** [faassen/howareyou#2]
I'm asking this because I have tried this benchmark against Falcon on PyPy, and results are:
howareyou -f falcon -n 10000000
Benchmark : hello
Frameworks: falcon
                ms     rps  tcalls  funcs
falcon       10051  994893      23     21
Benchmark was ran on Amazon EC2 1GB ram instance (with 1 CPU core)

**Comment by faassen** [comment]
"reliable" is a vague question. It's not doing any actual HTTP-level profiling, it stays at the Python and WSGI layer, so it doesn't have a lot of overhead. It doesn't translate into real world figures for that reason, and because in the real world you'd run multiple Python processes in parallel. PyPy's JIT can do a lot of optimization. I get this:

```
Benchmark : hello
Frameworks: falcon
                ms     rps  tcalls  funcs
falcon       12526  798370      23     21
```

It can also be faster the more iterations you run, as if you run the same code paths many times the JIT compiler's heuristics will consider it more worthwhile to create an optimized version of the function.

For all the frameworks (less iterations, more takes too long):

```
Frameworks: bottle, django, falcon, flask, morepath, pyramid, tornado, wheezy.web, wsgi
                ms     rps  tcalls  funcs
bottle         284  351892      54     32
django        2052   48735     186     86
falcon         184  543195      23     21
flask         6307   15856     281    128
morepath       663  150936      80     63
pyramid        588  170140      90     61
tornado       3778   26469     292    119
wheezy.web     187  533498      24     22
wsgi            76 1321357       8      8
```

It's interesting to see that Morepath is actually a bit slower than Pyramid on PyPy.

So this benchmark is interesting to measure framework overhead: how much a framework is doing, but it doesn't really give a real representation of how many requests per second you'll do in real-world conditions. A huge factor in this is of course your own application code.

**Comment by ghost** [comment]
@faassen I benchmarked with n = 10,000,000
for me morepath doesn't work

> Traceback (most recent call last):
>   File "/opt/pypy/bin/howareyou", line 9, in <module>
>     load_entry_point('howareyou==0.1.dev0', 'console_scripts', 'howareyou')()
>   File "/opt/pypy/site-packages/howareyou-0.1.dev0-py2.7.egg/howareyou/main.py", line 41, in main
>     run(benchmark, frameworks, args.number, args.profile)
>   File "/opt/pypy/site-packages/howareyou-0.1.dev0-py2.7.egg/howareyou/run.py", line 40, in run
>     **import**(framework)
>   File "/opt/pypy/site-packages/morepath/**init**.py", line 18, in <module>
>     from .core import (excview_tween_factory as EXCVIEW,
>   File "/opt/pypy/site-packages/morepath/core.py", line 33, in <module>
>     from .directive import App  # install directives with App
>   File "/opt/pypy/site-packages/morepath/directive.py", line 53, in <module>
>     @App.directive('setting')
> AttributeError: type object 'App' has no attribute 'directive'

**Comment by faassen** [comment]
Yes, I saw that, I benchmarked with that too. My machine's a bit slower than the amazon core you used, or alternatively perhaps your version of PyPy is a bit more optimized. But it's close enough.

**Comment by ghost** [comment]
@faassen I used last PyPy version from trunk (Python 2.7.10 (f8f3f559e826, Oct 08 2016, 22:09:54)
[PyPy 5.5.0-alpha0 with GCC 4.8.2] on linux2)  it's being built every day on pypy build bot
however, it's not generally stable
http://buildbot.pypy.org/nightly/trunk/

**Comment by faassen** [comment]
Yeah, I fixed the problem with the Morepath benchmark; the requirements.txt were out of date.
